import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import sanity from "@/lib/sanity";
import { NextPage } from "next";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

interface IProps {
  articles: any[];
  categories: any[];
}

const Home: NextPage<IProps> = ({ articles, categories }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-8">
        <h2 className="text-3xl font-bold">Articles</h2>
        <ul className="">
          {articles.map((article, index) => (
            <li key={index} className="flex flex-col justify-around items-star my-8 border-2 border-solid border-blue-400 rounded-lg py-2 px-4">
              <Link href={`article/${article.slug.current}`}>
                <h3 className="mb-2">{article.title}</h3>
                <p>{article.content}</p>
              </Link>
            </li>
          ))}
        </ul>

        <h2 className="text-3xl font-bold">Categories</h2>
        <div className="flex justify-around items-center my-4">
          {categories.map((category, index) => (
            <Link href={`category/${category.slug.current}`} key={index} className="text-blue-700 underline">
              <h3>{category.name}</h3>
            </Link>
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;

const articleQuery = `*[_type == "article"] {
  _id,
  title,
  slug,
  content,
  "categories": categories[]->{
    _id,
    name
  }
}`;

const categoryQuery = `*[_type == "category"] {
  _id,
  name,
  slug,
  "articles": articles[]->{
    _id,
    title,
  }
}`;

export const getStaticProps = async () => {
  const articles = await sanity.fetch(articleQuery);
  const categories = await sanity.fetch(categoryQuery);
  return {
    props: { articles, categories },
  };
};
